//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18444.
// 
#pragma warning disable 1591

namespace PdfBrowser.pl.gov.edeklaracje.test_bramka {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GateServiceSOAP11Binding", Namespace="https://bramka.e-deklaracje.mf.gov.pl/")]
    public partial class GateService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback sendDocumentOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendUnsignDocumentOperationCompleted;
        
        private System.Threading.SendOrPostCallback sendDocumentWithAttachmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback requestUPOOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GateService() {
            this.Url = global::PdfBrowser.Properties.Settings.Default.PdfBrowser_pl_gov_edeklaracje_test_bramka_GateService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event sendDocumentCompletedEventHandler sendDocumentCompleted;
        
        /// <remarks/>
        public event sendUnsignDocumentCompletedEventHandler sendUnsignDocumentCompleted;
        
        /// <remarks/>
        public event sendDocumentWithAttachmentCompletedEventHandler sendDocumentWithAttachmentCompleted;
        
        /// <remarks/>
        public event requestUPOCompletedEventHandler requestUPOCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sendDocument", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("sendDocumentResponse", Namespace="https://bramka.e-deklaracje.mf.gov.pl/xsd")]
        public sendDocumentResponse sendDocument([System.Xml.Serialization.XmlElementAttribute("sendDocument", Namespace="https://bramka.e-deklaracje.mf.gov.pl/xsd")] sendDocument sendDocument1) {
            object[] results = this.Invoke("sendDocument", new object[] {
                        sendDocument1});
            return ((sendDocumentResponse)(results[0]));
        }
        
        /// <remarks/>
        public void sendDocumentAsync(sendDocument sendDocument1) {
            this.sendDocumentAsync(sendDocument1, null);
        }
        
        /// <remarks/>
        public void sendDocumentAsync(sendDocument sendDocument1, object userState) {
            if ((this.sendDocumentOperationCompleted == null)) {
                this.sendDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendDocumentOperationCompleted);
            }
            this.InvokeAsync("sendDocument", new object[] {
                        sendDocument1}, this.sendDocumentOperationCompleted, userState);
        }
        
        private void OnsendDocumentOperationCompleted(object arg) {
            if ((this.sendDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendDocumentCompleted(this, new sendDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sendUnsignDocument", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("sendUnsignDocumentResponse", Namespace="https://bramka.e-deklaracje.mf.gov.pl/xsd")]
        public sendUnsignDocumentResponse sendUnsignDocument([System.Xml.Serialization.XmlElementAttribute("sendUnsignDocument", Namespace="https://bramka.e-deklaracje.mf.gov.pl/xsd")] sendUnsignDocument sendUnsignDocument1) {
            object[] results = this.Invoke("sendUnsignDocument", new object[] {
                        sendUnsignDocument1});
            return ((sendUnsignDocumentResponse)(results[0]));
        }
        
        /// <remarks/>
        public void sendUnsignDocumentAsync(sendUnsignDocument sendUnsignDocument1) {
            this.sendUnsignDocumentAsync(sendUnsignDocument1, null);
        }
        
        /// <remarks/>
        public void sendUnsignDocumentAsync(sendUnsignDocument sendUnsignDocument1, object userState) {
            if ((this.sendUnsignDocumentOperationCompleted == null)) {
                this.sendUnsignDocumentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendUnsignDocumentOperationCompleted);
            }
            this.InvokeAsync("sendUnsignDocument", new object[] {
                        sendUnsignDocument1}, this.sendUnsignDocumentOperationCompleted, userState);
        }
        
        private void OnsendUnsignDocumentOperationCompleted(object arg) {
            if ((this.sendUnsignDocumentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendUnsignDocumentCompleted(this, new sendUnsignDocumentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:sendDocumentWithAttachment", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("sendDocumentWithAttachmentResponse", Namespace="https://bramka.e-deklaracje.mf.gov.pl/xsd")]
        public sendDocumentWithAttachmentResponse sendDocumentWithAttachment([System.Xml.Serialization.XmlElementAttribute("sendDocumentWithAttachment", Namespace="https://bramka.e-deklaracje.mf.gov.pl/xsd")] sendDocumentWithAttachment sendDocumentWithAttachment1) {
            object[] results = this.Invoke("sendDocumentWithAttachment", new object[] {
                        sendDocumentWithAttachment1});
            return ((sendDocumentWithAttachmentResponse)(results[0]));
        }
        
        /// <remarks/>
        public void sendDocumentWithAttachmentAsync(sendDocumentWithAttachment sendDocumentWithAttachment1) {
            this.sendDocumentWithAttachmentAsync(sendDocumentWithAttachment1, null);
        }
        
        /// <remarks/>
        public void sendDocumentWithAttachmentAsync(sendDocumentWithAttachment sendDocumentWithAttachment1, object userState) {
            if ((this.sendDocumentWithAttachmentOperationCompleted == null)) {
                this.sendDocumentWithAttachmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendDocumentWithAttachmentOperationCompleted);
            }
            this.InvokeAsync("sendDocumentWithAttachment", new object[] {
                        sendDocumentWithAttachment1}, this.sendDocumentWithAttachmentOperationCompleted, userState);
        }
        
        private void OnsendDocumentWithAttachmentOperationCompleted(object arg) {
            if ((this.sendDocumentWithAttachmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sendDocumentWithAttachmentCompleted(this, new sendDocumentWithAttachmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:requestUPO", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("requestUPOResponse", Namespace="https://bramka.e-deklaracje.mf.gov.pl/xsd")]
        public requestUPOResponse requestUPO([System.Xml.Serialization.XmlElementAttribute("requestUPO", Namespace="https://bramka.e-deklaracje.mf.gov.pl/xsd")] requestUPO requestUPO1) {
            object[] results = this.Invoke("requestUPO", new object[] {
                        requestUPO1});
            return ((requestUPOResponse)(results[0]));
        }
        
        /// <remarks/>
        public void requestUPOAsync(requestUPO requestUPO1) {
            this.requestUPOAsync(requestUPO1, null);
        }
        
        /// <remarks/>
        public void requestUPOAsync(requestUPO requestUPO1, object userState) {
            if ((this.requestUPOOperationCompleted == null)) {
                this.requestUPOOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrequestUPOOperationCompleted);
            }
            this.InvokeAsync("requestUPO", new object[] {
                        requestUPO1}, this.requestUPOOperationCompleted, userState);
        }
        
        private void OnrequestUPOOperationCompleted(object arg) {
            if ((this.requestUPOCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.requestUPOCompleted(this, new requestUPOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://bramka.e-deklaracje.mf.gov.pl/xsd")]
    public partial class sendDocument {
        
        private byte[] documentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://bramka.e-deklaracje.mf.gov.pl/xsd")]
    public partial class sendDocumentResponse {
        
        private string refIdField;
        
        private int statusField;
        
        private string statusOpisField;
        
        /// <remarks/>
        public string refId {
            get {
                return this.refIdField;
            }
            set {
                this.refIdField = value;
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string statusOpis {
            get {
                return this.statusOpisField;
            }
            set {
                this.statusOpisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://bramka.e-deklaracje.mf.gov.pl/xsd")]
    public partial class sendUnsignDocument {
        
        private byte[] documentField;
        
        private sendUnsignDocumentLanguage languageField;
        
        private bool languageFieldSpecified;
        
        private sendUnsignDocumentSignatureType signatureTypeField;
        
        private bool signatureTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
        
        /// <remarks/>
        public sendUnsignDocumentLanguage language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool languageSpecified {
            get {
                return this.languageFieldSpecified;
            }
            set {
                this.languageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public sendUnsignDocumentSignatureType signatureType {
            get {
                return this.signatureTypeField;
            }
            set {
                this.signatureTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool signatureTypeSpecified {
            get {
                return this.signatureTypeFieldSpecified;
            }
            set {
                this.signatureTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://bramka.e-deklaracje.mf.gov.pl/xsd")]
    public enum sendUnsignDocumentLanguage {
        
        /// <remarks/>
        de,
        
        /// <remarks/>
        en,
        
        /// <remarks/>
        pl,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://bramka.e-deklaracje.mf.gov.pl/xsd")]
    public enum sendUnsignDocumentSignatureType {
        
        /// <remarks/>
        PIT,
        
        /// <remarks/>
        MPO,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://bramka.e-deklaracje.mf.gov.pl/xsd")]
    public partial class sendUnsignDocumentResponse {
        
        private string refIdField;
        
        private int statusField;
        
        private string statusOpisField;
        
        /// <remarks/>
        public string refId {
            get {
                return this.refIdField;
            }
            set {
                this.refIdField = value;
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string statusOpis {
            get {
                return this.statusOpisField;
            }
            set {
                this.statusOpisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://bramka.e-deklaracje.mf.gov.pl/xsd")]
    public partial class sendDocumentWithAttachment {
        
        private byte[] attachmentField;
        
        private byte[] documentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] attachment {
            get {
                return this.attachmentField;
            }
            set {
                this.attachmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://bramka.e-deklaracje.mf.gov.pl/xsd")]
    public partial class sendDocumentWithAttachmentResponse {
        
        private string refIdField;
        
        private int statusField;
        
        private string statusOpisField;
        
        /// <remarks/>
        public string refId {
            get {
                return this.refIdField;
            }
            set {
                this.refIdField = value;
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string statusOpis {
            get {
                return this.statusOpisField;
            }
            set {
                this.statusOpisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://bramka.e-deklaracje.mf.gov.pl/xsd")]
    public partial class requestUPO {
        
        private string refIdField;
        
        private requestUPOLanguage languageField;
        
        private bool languageFieldSpecified;
        
        /// <remarks/>
        public string refId {
            get {
                return this.refIdField;
            }
            set {
                this.refIdField = value;
            }
        }
        
        /// <remarks/>
        public requestUPOLanguage language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool languageSpecified {
            get {
                return this.languageFieldSpecified;
            }
            set {
                this.languageFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://bramka.e-deklaracje.mf.gov.pl/xsd")]
    public enum requestUPOLanguage {
        
        /// <remarks/>
        de,
        
        /// <remarks/>
        en,
        
        /// <remarks/>
        pl,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://bramka.e-deklaracje.mf.gov.pl/xsd")]
    public partial class requestUPOResponse {
        
        private string upoField;
        
        private int statusField;
        
        private string statusOpisField;
        
        /// <remarks/>
        public string upo {
            get {
                return this.upoField;
            }
            set {
                this.upoField = value;
            }
        }
        
        /// <remarks/>
        public int status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string statusOpis {
            get {
                return this.statusOpisField;
            }
            set {
                this.statusOpisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void sendDocumentCompletedEventHandler(object sender, sendDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public sendDocumentResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((sendDocumentResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void sendUnsignDocumentCompletedEventHandler(object sender, sendUnsignDocumentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendUnsignDocumentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendUnsignDocumentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public sendUnsignDocumentResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((sendUnsignDocumentResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void sendDocumentWithAttachmentCompletedEventHandler(object sender, sendDocumentWithAttachmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sendDocumentWithAttachmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sendDocumentWithAttachmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public sendDocumentWithAttachmentResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((sendDocumentWithAttachmentResponse)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void requestUPOCompletedEventHandler(object sender, requestUPOCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class requestUPOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal requestUPOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public requestUPOResponse Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((requestUPOResponse)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591